Merge branch 'upstream-main' into 'main'
* aosp/upstream-main:
  Abigail reader: use graph Maker helper
  graph: add Maker MaybeSet method
  graph: pass Maker methods external ID by reference
  graph: rename Maker Duplicate to DieDuplicate
  graph: inline Maker Define helper
  Abigail reader: move RemoveUselessQualifiers call out of ProcessRoot
  type normalisation: make RemoveUselessQualifiers return root node ID
  Abigail reader: refactor Read functions
  proto reader: time ReadFromString analogously to Read
  Abigail reader: time libxml contribution to ReadFromString
  proto and Abigail readers: add runtime parameter to ReadFromString
  proto reader: time the TextFormat Parse and STG Transform phases
  proto_reader: ReadFromString: drop useless parameter type qualifier and add a TODO
  Abigail reader: hide implementation
  Abigail reader: update documentation comments
  stgdiff: refactor some duplicate input processing code
  Abigail reader: factor ProcessDocument out of all users
  Abigail reader fuzzer: eschew abbreviated "doc"
  DWARF processor: use Hex<Dwarf_Off> as the type of external node IDs
  DWARF processor: use graph Maker helper
  proto reader: use Hex<uint32_t> IDs
  proto reader: use graph Maker for better error messages
  hex: add std::hash operator
  hex: add Hex comparison operators and test
  hex: Hex now just holds a value instead of a const reference
  hex: add Hex formatting tests
  hex: split Hex functionality out of error.h into hex.h
  BTF reader: build graph with Maker helper
  graph: add Maker helper class
  BTF reader: hide implementation
  BTF reader: add ReadSection interface
  proto reader: move GetId calls into templated AddNode helper function
  SCC: fix exception specification for destructor
  Abigail reader: add ReadFromString interface
  use C++20 starts_with and ends_with
  ELF reader: allow ELF without DWARF
  error: document split Check destructor
  error: split Check destructor for inlining
  proto writer: rework custom sort functions with forward_as_tuple
  ELF/DWARF handle: move error message formatting out of CheckOrDwflError
  BTF reader: use `ElfDwarfHandle` instead of loading `Elf` directly
  ELF reader: use `ElfDwarfHandle` as a single entry point
  ELF/DWARF handle: deduplicate constructors
  DWFL wrapper: refactor `dwarf::Handle` as `ElfDwarfHandle`
  DWARF processor: move `GetDwarf` to `dwarf::Process` callers
  DWARF reader: make `GetCompilationUnits` stand alone
  DWARF wrapper: get `Dwarf` on demand
  ELF loader: use `Elf` by reference
  no longer repeat return types in return expressions
  mark more local variables as const
  SCC: check state is clean in destructor
  stg: wrap comparison code within a diff namespace
  DWARF wrappers: add missing includes
  DWARF wrappers: check for nullptr
  BTF reader: use mmap to read BTF file and force data alignment
  ELF loader: replace GetBtfRawData with GetSectionRawData and GetRawData
  ELF loader: GetBtfRawData: code cleanups
  ELF reader: split Linux / userspace symbol table handling
  DWARF processor: rework ELF / DWARF matching error messages
  DWARF processor: make Types::Symbol::linkage_name non-optional
  DWARF processor: rename Type::Symbol members for clarity
  replace std:: count with C++20 contains and binary_search
  test cases: rework tweaked tests
  test cases: pointer-to-member: define member function
  test cases: simplify variable length array test
  ELF reader: add const where possible
  DWARF reader: remove `static` from constant in anonymous namespace
  ELF/DWARF reader: remove unused headers
  DWARF wrapper: remove `elf_memory` workaround

Signed-off-by: Giuliano Procida <gprocida@google.com>
Change-Id: I5254e867c22cc95f7b3e98e13fc16d8092ec97bf