Autoupdate of 3 submodules
*trusty/device/x86/generic-x86_64 updated to e88bccac234023285ca77fb6ebed60b83835c901
vm-x86_64*: Fix incorrect architecture typos

This change fixes the Makefile includes to point to correct
architectures

Bug: 399565091
Test: /trusty/vendor/google/aosp/scripts/build.py vm-x86_64-test_os --jobs 129
Change-Id: I31f1bdbc610c8c114727b31d76de8ff788979ae8

*trusty/user/base updated to 95273a9e96cf696a322398ffa3f28b59216653a1
make/library.mk: Trigger copying the headers on configheader changes

Before aosp/3527960, vm-x86_64-test_os built arm64 targets. Unfortunately, the
change does not trigger a full rebuild but causes the incremental build to fail
with:

external/trusty/musl/src/internal/floatscan.c:150:17: error: magnitude of floating-point constant too large for type 'long double'; maximum is 1.18973149535723176502E+4932 [-Werror,-Wliteral-range]
  150 |                 return sign * LDBL_MAX * LDBL_MAX;
      |                               ^
... build-root/build-vm-x86_64-test_os-userdebug/sdk/sysroot//usr/include/bits/float.h:5:18: note: expanded from macro 'LDBL_MAX'
    5 | #define LDBL_MAX 1.18973149535723176508575932662800702e+4932L
      |                  ^

This change introduces a dependency on copied headers to configheader
to detect build configuration changes.

Bug: 399565091
Test: build.py vm-x86_64-test_os-userdebug
Change-Id: If2b55a9774bb84285361b6dc319295b21120bcda

*external/trusty/lk updated to 0dd02aa6291a32da7abb74bae017a4ed5f589a31
make/module.mk: Trigger module rebuild on ARCH changes

Before aosp/3527960, vm-x86_64-test_os built arm64 targets. Unfortunately, the
change does not trigger a full rebuild but causes the incremental build to fail.

This change introduces a dependency on rust module config to a ARCH variable
to detect ARCH change during incremental build.

Bug: 399565091
Test: build.py vm-x86_64-test_os-userdebug
Change-Id: If2b55a9774bb84285361b6dc319295b21120bcda