gfxstream: look for common/opengl headers
Probably "Make GL header lib and update libs to explicitly
depend on it" broke the meson build.

In file included from ../renderControl_enc/renderControl_types.h:19,
                 from ../renderControl_enc/renderControl_client_proc.h:8,
                 from ../renderControl_enc/renderControl_client_context.h:6,
                 from ../renderControl_enc/renderControl_enc.h:9,
                 from ../vulkan_enc/../OpenglSystemCommon/HostConnection.h:25,
                 from ../vulkan_enc/ResourceTracker.cpp:19:
../OpenglCodecCommon/glUtils.h:46:10: fatal error: GLES/gl.h: No such file or directory

Long term, we should nuke renderControl and GL dependencies through
compile options (GOLDFISH_NO_GL) for example.

BUG=311486792
TEST=meson amd64-build/
     ninja -C amd64-build

Change-Id: Ifebac059e51d527423e66f7e3ba6e7a73b8bcfa3